### ISSUE TITLE
haxe version.

### ISSUE THREAD

**Issue by IanSSenne** [FurretDev/hx_webserver#3]
hi, I'm having issues running your test.hxml file, what version of haxe is it meant to be using?
windows running 4.3.1 i get this
```bash
./hx_webserver/FormdataRequest.hx:38: characters 45-58 : Default argument value should be constant
```
and wsl running 4.2.5 gets the following
```bash
./hx_webserver/RouteMap.hx:33: characters 17-18 : Unexpected )
```

**Comment by furretpaws** [comment]
Try to use the haxelib release
`haxelib install hx_webhserver 0.0.3`

**Comment by IanSSenne** [comment]
hi @FurretDev I'm trying to make a change to submit a pr so using the haxelib release isn't really an option for me.

**Comment by furretpaws** [comment]
hmm okay, i'll check it out then (since I have moved to arch linux I'm not using the git version anymore, that's why i haven't got any issues)

**Comment by IanSSenne** [comment]
hi @FurretDev, I didn't want to make a pr until i could get the tests running locally but it seems that might take a bit, if your interested in implimenting it I used the `mime-db` npm package to compile a more complete list of mime types. https://github.com/FurretDev/hx_webserver/compare/main...IanSSenne:hx_webserver:main if you want me to make this into a pr please let me know otherwise I'll just leave it be for the time being.

Have a good day :)

**Comment by furretpaws** [comment]
sorry for the delay in answering, go ahead and make a pr if you want, contributions are always welcome<3

**Comment by furretpaws** [comment]
i'm closing the issue due to inactivity :p
